name: Validate commit

run-name: Validating commit ${{ github.sha }} from ${{ github.actor }}

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm run test
      - run: pnpm run lint
